name: Java CI
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        platform: [ ubuntu-latest ]
    runs-on: ${{matrix.platform}}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build and Test
        working-directory: .
        run: mvn test
